[project]
name = "proxy-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["python-dotenv>=1.2.1"]

[project.optional-dependencies]
mihomo = ["pyyaml>=6.0.3"]
